version: '3.8'

services:
  fast-rat:
    build: .
    container_name: fast-rat-app
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Africa/Cairo
